#pragma once

#define GAUSSIANBLUR 5
#define CARDCANNY_1 10
#define CARDCANNY_2 100
#define CARDCONTOURS 1000
#define CARDRATIO_MIN 1.0
#define CARDRATIO_MAX 2.0

#define CHARRECT_X 15
#define CHARRECT_Y 100
#define CHARRECT_WIDTH 300
#define CHARRECT_HEIGHT 65
#define CHARCANNY_1 10
#define CHARCANNY_2 100
#define CHARBIGSIZE_WIDTH 75*4
#define CHARBIGSIZE_HEIGHT 20*4
#define COUNTNONZERO_ROW 53
#define COUNTNONZERO_COL 2
#define CHARCONTOURS 30
#define ONECHARRECT_HEIGTH 20
#define ONECHARRECT_WIDTH 15
#define ONECHARRECT_WIDTH_NUM 12

